# Spring配置
spring:
  profiles:
    active: test
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  150MB
      # 设置总上传的文件大小
      max-request-size:  200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

# 日志配置
logging:
  level:
    com.oaker: debug
    org.springframework: warn

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 120

user:
  session:
    header: Authorization
springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.oaker.**.domain
  configuration:
    map-underscore-to-camel-case: true
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.oaker
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    #驼峰下划线转换
    db-column-underline: true

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


justauth:
  enabled: true
  type:
    QQ:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/qq
      union-id: false
    WEIBO:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/weibo
    GITEE:
      client-id: 3c24d15a38a436f7a3abae8b640528fe6081563808e026dd4a540cad39137ec1
      client-secret: 745f22531c21f67750427dbcfcf61428afd58f46fe830645af896c5b42ed4315
      redirect-uri: http://127.0.0.1:8080/oauth/callback/gitee
    DINGTALK:
      client-id: 2711706041
      client-secret: e5fiseg3fA0UccDlmw6UfEmpxq5OQSHpZMlJKfS9rUsd0wCd_RMlSNHCk-y_-43b
      redirect-uri: http://127.0.0.1:8080/oauth/callback/dingtalk
    BAIDU:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/baidu
    CSDN:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/csdn
    CODING:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/coding

    OSCHINA:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/oschina
    ALIPAY:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/alipay
      alipay-public-key: MIIB**************DAQAB
    WECHAT_OPEN:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/wechat_open
    WECHAT_MP:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/wechat_mp
    WECHAT_ENTERPRISE:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/wechat_enterprise
      agent-id: 1000002
    TAOBAO:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/taobao
    GOOGLE:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/google
    FACEBOOK:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/facebook
    DOUYIN:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/douyin
    LINKEDIN:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/linkedin
    MICROSOFT:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/microsoft
    MI:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/mi
    TOUTIAO:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/toutiao
    TEAMBITION:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/teambition
    RENREN:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/renren
    PINTEREST:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/pinterest
    STACK_OVERFLOW:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/stack_overflow
      stack-overflow-key: asd*********asd
    HUAWEI:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/huawei
    KUJIALE:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/kujiale
    GITLAB:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/gitlab
    MEITUAN:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/meituan
    ELEME:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/eleme
    TWITTER:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://127.0.0.1:8080/oauth/callback/twitter

  cache:
    type: default